### ISSUE TITLE
Not all taxa have N & P values 

### ISSUE THREAD

**Issue by efcaguab** [jagephart/FishPrint#1]
Hi there, I was checking the species for which there are fish nutrients contents from the `fish_NP_clean.csv` output file as well as the `lca_clean_with_groups.csv`. 

I'm using the later file to determine the taxa for which the tool can produce estimates (based on `clean_sci_name`). However, I found there are two taxa (both seaweeds) for which there is no information in the `fish_NP_clean.csv` table. 

If I understand correctly, the nitrogen and phosphorus content of a species is needed to estimate the on-farm values for nutrient stressors.

**Comment by jagephart** [comment]
These values are manually assigned in one of the scripts (I would have to look back to find these).
